name: SHADYINVESTOR
favicon: null
layout_spectrum: 0.23013
typography_spectrum: 0.34063280932605267
title: CONFESSIONS OF THE SHADY INVESTOR
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#72b63e'
    - '#111515'
    - '#ffffff'
    - '#007f24'
    - '#b8da9e'
  brandStrength: 0.5
  lightness: 0.9940786550287157
  saturation: 0.2408738301601261
  rhythmicContrast: 0.5116842200513929
purpose: []
